version: '3.3'
services:
  db:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: 'myappdb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - 8087:80
    environment:
      - PMA_ARBITRARY=1
#  app:
#    container_name: app
#    image: appflask:latest
#    restart: always
#    ports:
#      - 5050:5050

volumes:
  db-data:
